# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadsample():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_downloadsample(self):
    self.driver.get("https://y2down.cc/enV8/youtube-wav")
    self.driver.set_window_size(749, 578)
    self.driver.find_element(By.CSS_SELECTOR, ".input-url").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-quality").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".btn-quality")
    dropdown.find_element(By.XPATH, "//option[. = 'WAV']").click()
    self.driver.find_element(By.CSS_SELECTOR, "optgroup:nth-child(2) > option:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-url").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-url").send_keys("https://www.youtube.com/watch?v=hbPpo7d-nQg")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#load > span").click()
    self.vars["win3804"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win3804"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".btn-download:nth-child(3) > span").click()
  
